server:
  port: 80
  tomcat:
      max-threads: 800 # tomcat最大线程数，默认为200
      uri-encoding: UTF-8
      basedir: ../tmp #存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
      accesslog:
        enabled: true
spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    account:
      path: /account/**
      serviceId: service-account
    place:
      path: /place/**
      serviceId: service-place